version: "3.8"
services:


  log_generator:
    build:
      context: ./services/log_generator
    container_name: log_generator
    volumes:
      - logs:/logs
    environment:
      - LOG_INTERVAL=1
    restart: "no"
    mem_limit: 128m
    cpus: "0.50"


  log_processor:
    build:
      context: ./services/log_processor
    container_name: log_processor
    volumes:
      - logs:/logs
      - processed:/processed
    depends_on:
      - log_generator
    restart: "no"
    mem_limit: 128m
    cpus: "0.50"


  log_analyzer:
    build:
      context: ./services/log_analyzer
    container_name: log_analyzer
    volumes:
      - processed:/processed
      - reports:/reports
    depends_on:
      - log_processor
    restart: "no"
    mem_limit: 128m
    cpus: "0.50"


volumes:
  logs:
  processed:
  reports: